### ISSUE TITLE
DihedralFeaturizer.describe_features fails for atom_slices

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#739] opened 2016-02-20 01:39 UTC
Error is thrown at [featurizer.py#L539](https://github.com/msmbuilder/msmbuilder/blob/db27e6f8adfb6c3c3167f763c15581c57e318c90/msmbuilder/featurizer/featurizer.py#L539) because `resnames` is being populated using `resid` rather than `range(traj.n_residues)`.

**Comment by mpharrigan** [comment] 2016-02-20 02:26
cc #677

**Comment by mpharrigan** [comment] 2016-03-16 23:33
@msultan can you check this with the newest #677

**Comment by mpharrigan** [comment] 2016-03-24 01:21
Is this fixed with #769

**Comment by msultan** [comment] 2016-03-24 06:14
No idea. I need a pdb to test this on.

**Comment by cxhernandez** [comment] 2016-03-24 14:15
You can test with any structure. This wasn't an issue with a specific PDB, just with an atom slice of a system.

**Comment by msultan** [comment] 2016-03-24 16:59
So this is more tricker that I thought it would be. The problem is that when you use ```md.load``` with atom_slice the residue indices _are_ maintained. 
```python
fs = FsPeptide()
fs.cache()
dirname = fs.data_dir
top = md.load(dirname+"/fs-peptide.pdb")
atom_ind=[i.index for i in top.top.atoms if i.residue.is_protein
          and (i.residue.index in range(15) or i.residue.index in range(20,23))]
trajectories = [md.load(fn, stride=100, top=top,atom_indices=atom_ind) for fn in
                glob.glob(os.path.join(dirname,"trajectory*.xtc"))]
In [54]: t = trajectories[0]
In [55]: print([i.index for i in t.top.residues])
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 20, 21, 22]
```

But when you try and access for example the 20th residue, it fails. 
```python
In [56]: t.top.residue(20)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-56-cf3abe9ba220> in <module>()
----> 1 t.top.residue(20)

/Users/muneeb/anaconda/lib/python3.5/site-packages/mdtraj/core/topology.py in residue(self, index)
    697             The `index`-th residue in the topology.
    698         """
--> 699         return self._residues[index]
    700 
    701     @property

IndexError: list index out of range

```
So there is an internal residue indexing and an external residue indexing as far as I can tell.

**Comment by cxhernandez** [comment] 2016-03-24 17:17
Right so instead of iterating over `[i.index for i in t.top.residues]`, we should be iterating over `range(t.n_residues)` and map back to the original residue indexing when necessary.

**Comment by msultan** [comment] 2016-03-24 17:21
I tried a fix, which seems to work, where I am iterating over the atom indices instead.  However, it is returning the residue indices that are not 0-indexed

**Comment by msultan** [comment] 2016-03-24 17:22
iterating over the ```range(t.n_residues)``` might open a can of worms where i would need to check the topology and what not.

**Comment by cxhernandez** [comment] 2016-03-24 17:27
> However, it is returning the residue indices that are not 0-indexed

I think that's fine

**Comment by mpharrigan** [comment] 2016-03-25 20:28
Is this fixed with #769

**Comment by msultan** [comment] 2016-03-25 20:29
yes, the tests are now randomly checking either a full FS peptide trajectory or a atom sliced trajectory for feature calculation equivalence.

**Comment by mpharrigan** [comment] 2016-03-25 20:30
Please close the issue

**Closed** 2016-03-25 20:31 UTC
