### ISSUE TITLE
Using subset of common atoms for rmsd-based clustering

### ISSUE THREAD

**Issue by jeiros** [msmbuilder/msmbuilder#1021] opened 2017-07-04 13:49 UTC
Hi,

I've simulated a protein in three phosphorylation states, and I'm using the scripts provided by `msmb TemplateProject` to do the analysis. I've found the `msmbuilder.io` way of dealing with several simulations using metadata objects very convenient!

Since the topologies are not the same, I'm using a subset of common atoms to do the analysis. For this, I've modified the `preload_tops` and `itertrajs` functions of the `msmbuilder.io` module to work with a subset of common atoms. The indices of the common atoms (alpha carbons of the backbone, in my case) are also not identical between the three systems because the different atoms in the phosphorylated residues that I have affect the numbering.

```python
def preload_tops(meta, selection='all'):
    """Custom preload_tops function

    Load all topology files into memory.
    This might save some performance compared to re-parsing the topology
    file for each trajectory you try to load in. Typically, you have far
    fewer (possibly 1) topologies than trajectories
    Parameters
    ----------
    meta : pd.DataFrame
        The DataFrame of metadata with a column named 'top_fn'
    selection: str
        The atom selection
    Returns
    -------
    tops : dict
        Dictionary of 2d tuples keyed by "top_fn". The first element of the
        tuple is a ``md.Topology`` object, the second are the atom indices in
        ``np.array`` form, corresponding to parameter selection  values.
    """
    top_fns = set(meta['top_fn'])
    tops = {}
    for tfn in top_fns:
        tops[tfn] = (md.load_topology(tfn), md.load_topology(tfn).select(selection))
    return tops

def itertrajs(meta, selection='all', stride=1):
    """Custom itertrajs function

    Load one mdtraj trajectory at a time and yield it.
    MDTraj does striding badly. It reads in the whole trajectory and
    then performs a stride. We join(iterload) to conserve memory.
    """

    tops = preload_tops(meta, selection=selection)
    for i, row in meta.iterrows():
        yield i, md.join(md.iterload(row['traj_fn'],
                                     top=tops[row['top_fn']][0],
                                     atom_indices=tops[row['top_fn']][1],
                                     stride=stride),
                         discard_overlapping_frames=False,
                         check_topology=False)
```
So now this is able to load the same common atoms for the different systems in the metadata object:
```python
meta = load_meta()
list(itertrajs(meta, selection='name CA', stride=100))
```
```
[(0,
  <mdtraj.Trajectory with 73 frames, 419 atoms, 419 residues, and unitcells at 0x11296b0f0>),
 (1,
  <mdtraj.Trajectory with 73 frames, 419 atoms, 419 residues, and unitcells at 0x11c2e8e10>),
 (2,
  <mdtraj.Trajectory with 73 frames, 419 atoms, 419 residues, and unitcells at 0x11c2e8f98>),
...]
```

The problem comes from trying to use `MiniBatchKMedoids` clustering from `msmbuilder.cluster`. I _think_ setting the `metric` attribute to `'rmsd'` should work, but I'm getting an error about the topologies not being the same (which they aren't, but shouldn't the RMSD be computable anyway if the same amount of atoms are given?):
```python
kmed = MiniBatchKMedoids(
    n_clusters=500,
    metric='rmsd',
)
kmed.fit([traj for _, traj in itertrajs(meta=meta, selection='name CA', stride=100)])
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-cba2d33eb2e3> in <module>()
      3     metric='rmsd',
      4 )
----> 5 kmed.fit([traj for _, traj in itertrajs(meta=meta, selection='name CA', stride=100)])

~/miniconda3/lib/python3.6/site-packages/msmbuilder/cluster/minibatchkmedoids.py in fit(self, sequences, y)
    198         self
    199         """
--> 200         MultiSequenceClusterMixin.fit(self, sequences)
    201         self.cluster_ids_ = self._split_indices(self.cluster_ids_)
    202         return self

~/miniconda3/lib/python3.6/site-packages/msmbuilder/cluster/base.py in fit(self, sequences, y)
     46         """
     47         check_iter_of_sequences(sequences, allow_trajectory=self._allow_trajectory)
---> 48         super(MultiSequenceClusterMixin, self).fit(self._concat(sequences))
     49 
     50         if hasattr(self, 'labels_'):

~/miniconda3/lib/python3.6/site-packages/msmbuilder/cluster/base.py in _concat(self, sequences)
     65             concat = sequences[:][0]
     66             if len(sequences) > 1:
---> 67                 concat = concat.join(sequences[:][1:])
     68             concat.center_coordinates()
     69         else:

~/miniconda3/lib/python3.6/site-packages/mdtraj/core/trajectory.py in join(self, other, check_topology, discard_overlapping_frames)
   1014                           'to number of atoms in other' % (self.n_atoms))
   1015             if check_topology and not all(self.topology == o.topology for o in other):
-> 1016                 raise ValueError('The topologies of the Trajectories are not the same')
   1017             if not all(self._have_unitcell == o._have_unitcell for o in other):
   1018                 raise ValueError('Mixing trajectories with and without unitcell')

ValueError: The topologies of the Trajectories are not the same
```

Is there a possible workaround to this? Or do I have to do the analysis for each phosphorylation state on its own? The reason I wanted to do this was to see if there are any shared clusters amongst the different states (which I think makes sense since I'm not changing the system that much).

**Comment by msultan** [comment] 2017-07-04 17:54
Right, I think the problem is that the trajectory object still have information about the phosphorylation state which is throwing the system. There are several options here. 

1). Pre-slice the trajectories to just CA atoms which should allow work. To test this out, try the following code first. 

``` python
import mdtraj as md 
t1 = md.load("protein_1.pdb")
t2 = md.load("protein_2.pdb")
t1 = t1.atom_slice([i.index for i in t1.top.atoms if i.name=='CA'])
t2 = t2.atom_slice([i.index for i in t2.top.atoms if i.name=='CA'])
ca_rmsd = md.rmsd(t2,t1)
```

2). Use a non-RMSD based metric, something like CA-distances  + tICA will work across all systems and give you the slowest modes that are common to _all_ three. Then you can use KMeans to make a single cluster set, and build MSM for each sequence/Phos- state separately to see which states are more accessible. 

``` python
t1 = md.load("protein_1.pdb")
t2 = md.load("protein_2.pdb")

#the featurizer figures out what the CA atoms are on the fly so no need to worry about sequence 
# as long as you dont have weird deletions/insertions going on
f1 = ContactFeaturizer(scheme='CA')

# compute features 
t1_feat = f1.featurize([t1])
t2_feat = f1.featurize([t2])

tica_mdl = tICA(lagtime=1)
#get the joint tica features
tica_feat = tica_mdl.fit_transform([f1_feat, f2_feat])

#joint kmeans mdl
kmeans_mdl = KMeans(n_clusters=10)
assignments = kmeans_mdl.fit_transform(tica_feat)

# build individual MSMs
msm_t1 = MarkovStateModel(lagtime=1)
msm_t2 = MarkovStateModel(lagtime=1)

# 0 is for t1, 1 is for t2. 
msm_t1.fit_transform(assignments[0])

msm_t2.fit_transform(assignments[1])

# now msm_t1.populations_ can be directly compared against msm_t2.populations_ to see what states are more when the data arises. Also, you can use MSMExplorer to plot the data along tICs/PCs to see what areas of phase space are getting more populated due to the perturbation. 
```

I have done something very similar for [kinases](http://www.biorxiv.org/content/early/2017/05/09/135913) and it works really nicely. Also, allows you to calculate dynamical properties like MFPT as a function of phosphorylation state etc. 

ps The code above might have mispelled attributes/API calls so please validate it .

**Comment by jeiros** [comment] 2017-07-05 07:52
Thank you so much for the detailed answer @msultan ! I'll give it a try and report back. It turns out I had 'solved' the problem by slicing the topologies to just CA atoms and saved the only CA atoms trajectory in disk. But knowing about `atom_slice` should make this easier 😄

**Comment by cing** [comment] 2017-07-22 08:20
Is it possible replicate this joining/splitting process when using the datasets API pattern? Dataset objects don't seem to be designed for such actions.

**Comment by msultan** [comment] 2017-07-22 18:44
hmm, I am dont think so but I am not sure. As far as i can tell, the dataset [object](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/dataset.py#L158) only supports ```fit``` and ```transform``` attributes instead of ```partialfit``` and ```partialtransform```. A PR for that would be very welcome here! 
Maybe other @msmbuilder/developers can chime in here too.

**Comment by msultan** [comment] 2017-08-10 18:29
Can i close this now?

**Comment by jeiros** [comment] 2017-08-10 19:24
Yep! Many thanks for helping out

On 10 Aug 2017 8:29 p.m., msultan <notifications@github.com> wrote:

Can i close this now?

**Closed** 2017-08-10 19:54 UTC

**Comment by hkohestani** [comment] 2018-02-28 19:56
Hi everyone,
maybe irrelevant to this topic but I am new with msmexplorer and msmbuilder and I am trying to use RMSDfeaturizer instead of Dihedral -- I am wondering why all these examples are for for dihedral-- I replaced the featurization part of msmexplorer markov network plotting with RMSDfeaturization but whatever I change for different transformations I get error. I know that for RMSD we should use partial transformation but what next for tICA? 

import mdtraj as md
import pickle
import numpy as np
import msmexplorer as msme

from msmbuilder.io import load_trajs, save_meta, load_generic, load_meta, preload_top, save_trajs, itertrajs, save_generic
from msmbuilder.featurizer import RMSDFeaturizer 
from msmbuilder.decomposition import tICA 
from msmbuilder.cluster import MiniBatchKMeans
from msmbuilder.msm import MarkovStateModel

rs = np.random.RandomState(42)

#load trajectory
ref = md.load("top.pdb")
traj = md.load("trajectory-1.dcd", top="top.pdb")

#rmsdfeaturizer

featurizer = RMSDFeaturizer(reference_traj=traj)
rmsds = featurizer.partial_transform(traj)


#perform dimension reduction

tica_model = tICA(lag_time=0.002, n_components=2)
tica_traj = tica_model.partial_fit(rmsds)

#411 
clusterer = MiniBatchKMeans(n_clusters=25, random_state=rs)
clustered_trajs = cluster.fit_transform(tica_traj)

#construct MSM

msm = MarkovStateModel(lag_time=0.002)
msm.fit(clustered_trajs)

#plot MSM Network

pos = dict(zip(range(clusterer.n_clusters), clusterer.cluster_centers_))
msme.plot_msm_network(msm, pos=pos, node_color='pomegranate', edge_color='carbon')



what maybe problem? thank you in advance

**Comment by msultan** [comment] 2018-03-02 16:20
Could you please print the actual error? its hard to solve the problem if we dont know what the error even is.

**Comment by hkohestani** [comment] 2018-03-02 17:03
HI Sultan,

thank you for your reply. i have attached the script. i tried to use
msmexplorer because its gonna give me pretty straightforward visualization
at the end i guess but my main problem is rmsdfeaturizer to tica. maybe i
need to add extra commands for featurization but as  I am totally new with
this package and somehow python i got a bit confused. any pointers or help
will be of great importance for me and i appreciate it.

here is the error:


  from pandas.core import datetools
ref loaded
traj loaded
featurized
Traceback (most recent call last):
  File "./msm_network.py", line 30, in <module>
    tica_traj = tica_model.fit_transform(rmsds)
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py",
line 398, in fit_transform
    self.fit(sequences)
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py",
line 282, in fit
    check_iter_of_sequences(sequences, max_iter=3)  # we might be
lazy-loading
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/utils/validation.py",
line 55, in check_iter_of_sequences
    raise ValueError('sequences must be a list of sequences')
ValueError: sequences must be a list of sequences


i tried to check different styles of transformation for rmsd or tica but
none of them worked. and i want to feed one long tranjectory (which is
combination of several trajectories....pooling them in one).

thank you in advance : )

Havva

**Comment by msultan** [comment] 2018-03-02 17:05
ahh, replace 

```
    tica_traj = tica_model.fit_transform(rmsds)

```
with
```
    tica_traj = tica_model.fit_transform([rmsds])
```

i think you only have 1 trajectory which is fine but msmbuilder was designed around fitting models to list/group of trajectories.

**Comment by hkohestani** [comment] 2018-03-02 17:19
from pandas.core import datetools
ref loaded
traj loaded
featurized
Traceback (most recent call last):
  File "./msm_network.py", line 30, in <module>
    tica_traj = tica_model.fit_transform([rmsds])
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py",
line 398, in fit_transform
    self.fit(sequences)
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py",
line 284, in fit
    self._fit(X)
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/decomposition/tica.py",
line 417, in _fit
    self._outer_0_to_T_lagged += np.dot(X[:-self.lag_time].T,
X[self.lag_time:])
TypeError: slice indices must be integers or None or have an __index__
method


here is new error

so you mean if i break my trajectory to groups it will be fine?

**Comment by msultan** [comment] 2018-03-02 17:22
replace
``` 
rmsds = featurizer.partial_transform(traj)
```
with 

```
rmsds = featurizer.partial_transform([traj])
```

and then type ```print(rmsds[0].shape)```. I want to know how many different features you have in your featurizer.

**Comment by hkohestani** [comment] 2018-03-02 18:08
this is what i got:


  from pandas.core import datetools
ref loaded
traj loaded
Traceback (most recent call last):
  File "msm_network.py", line 23, in <module>
    rmsds = featurizer.partial_transform([traj])
  File
"/home/evevenus/anaconda3/lib/python3.6/site-packages/msmbuilder/featurizer/featurizer.py",
line 314, in partial_transform
    sliced_traj = traj.atom_slice(self.atom_indices)
AttributeError: 'list' object has no attribute 'atom_slice'
