### ISSUE TITLE
return eigenvalue scalings for sparseTICA.transform

### ISSUE THREAD

**Issue by cxhernandez** [msmbuilder/msmbuilder#742] opened 2016-02-23 23:18 UTC
I've gotten better clustering/MSM results for my data after converting sparseTICA output into z-scores.

Is there any reason this hasn't been implemented?

**Comment by mpharrigan** [comment] 2016-02-24 00:16
Why did you close this?

**Comment by rmcgibbo** [comment] 2016-02-24 00:18
you should use the proper eigenvalue scaling from Frank + Cecilia's paper, not z-scores.

**Comment by cxhernandez** [comment] 2016-02-24 00:29
@mpharrigan: I realized that z-scores didn't actually change the result (which makes sense in hindsight) and it was something I had implemented poorly.

@rmcgibbo: [This one](http://arxiv.org/abs/1506.06259)?

**Comment by rmcgibbo** [comment] 2016-02-24 00:29
@cxhernandez yes.

**Comment by mpharrigan** [comment] 2016-03-16 23:23
duplicate of #605

**Closed by mpharrigan** 2016-03-16 23:23 UTC
Labels: enhancement, question
